export default function handler(req, res) {
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  
  const html = [
    '<!DOCTYPE html>',
    '<html>',
    '<head>',
    '<meta charset="UTF-8">',
    '<title>Catalogo Jana Dalecos</title>',
    '<style>',
    'body { font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }',
    'h1 { color: #333; border-bottom: 3px solid #0066cc; padding-bottom: 10px; }',
    'h2 { color: #0066cc; margin-top: 30px; }',
    'ul { list-style: none; padding: 0; }',
    'li { margin: 15px 0; }',
    'a { color: #0066cc; text-decoration: none; font-weight: bold; }',
    'a:hover { text-decoration: underline; }',
    '.preco { color: #22aa22; font-size: 18px; margin-top: 5px; }',
    '</style>',
    '</head>',
    '<body>',
    '',
    '<h1>📦 Catálogo Jana Dalecos</h1>',
    '',
    '<h2>Jalecos Masculinos</h2>',
    '<ul>',
    '<li><a href="https://www.danajalecos.com.br/shop/jalecos/masculinos/samuel/jaleco-samuel-amarelo/">Jaleco Masculino Samuel Amarelo</a><div class="preco">R$ 145,00 no PIX</div></li>',
    '<li><a href="https://www.danajalecos.com.br/shop/jalecos/masculinos/samuel/jaleco-samuel-azul/">Jaleco Masculino Samuel Azul</a><div class="preco">R$ 145,00 no PIX</div></li>',
    '<li><a href="https://www.danajalecos.com.br/shop/jalecos/masculinos/samuel/jaleco-samuel-verde/">Jaleco Masculino Samuel Verde</a><div class="preco">R$ 145,00 no PIX</div></li>',
    '<li><a href="https://www.danajalecos.com.br/shop/jalecos/masculinos/manoel/jaleco-manoel-azul-marinho/">Jaleco Masculino Manoel Azul Marinho</a><div class="preco">R$ 209,00 no PIX</div></li>',
    '</ul>',
    '',
    '<h2>Jalecos Femininos</h2>',
    '<ul>',
    '<li><a href="https://www.danajalecos.com.br/shop/jalecos/femininos/giovana/jaleco-giovana-rosa/">Jaleco Feminino Giovana Rosa</a><div class="preco">R$ 165,00 no PIX</div></li>',
    '<li><a href="https://www.danajalecos.com.br/shop/jalecos/femininos/giovana/jaleco-giovana-azul/">Jaleco Feminino Giovana Azul</a><div class="preco">R$ 165,00 no PIX</div></li>',
    '</ul>',
    '',
    '<h2>Scrubs</h2>',
    '<ul>',
    '<li><a href="https://www.danajalecos.com.br/shop/scrubs/masculinos/pedro/scrub-pedro-azul/">Scrub Masculino Pedro Azul</a><div class="preco">R$ 177,65 no PIX</div></li>',
    '<li><a href="https://www.danajalecos.com.br/shop/scrubs/masculinos/pedro/scrub-pedro-verde/">Scrub Masculino Pedro Verde</a><div class="preco">R$ 177,65 no PIX</div></li>',
    '<li><a href="https://www.danajalecos.com.br/shop/scrubs/femininos/ana/scrub-ana-rosa/">Scrub Feminino Ana Rosa</a><div class="preco">R$ 145,35 no PIX</div></li>',
    '</ul>',
    '',
    '<h2>Gorros</h2>',
    '<ul>',
    '<li><a href="https://www.danajalecos.com.br/shop/gorros/cirurgicos/gorro-verde/">Gorro Cirúrgico Verde</a><div class="preco">R$ 45,00 no PIX</div></li>',
    '<li><a href="https://www.danajalecos.com.br/shop/gorros/cirurgicos/gorro-azul/">Gorro Cirúrgico Azul</a><div class="preco">R$ 45,00 no PIX</div></li>',
    '</ul>',
    '',
    '<p style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc; color: #666; font-size: 12px;">',
    'Total de produtos: 11 | Última atualização: ' + new Date().toLocaleDateString('pt-BR') + '',
    '</p>',
    '',
    '</body>',
    '</html>'
  ].join('\n');
  
  res.status(200).send(html);
}
