export default function handler(req, res) {
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  
  const html = [
    '<!DOCTYPE html>',
    '<html>',
    '<head>',
    '<meta charset="UTF-8">',
    '<title>Teste 3 Versoes - Stevo</title>',
    '</head>',
    '<body>',
    '',
    '<h1 style="background: lightgreen; padding: 15px;">TESTE: Qual versao o Stevo consegue ler?</h1>',
    '',
    '<hr style="border: 3px solid black;">',
    '<h2 style="background: yellow; padding: 10px;">VERSAO 1: HTML PURO</h2>',
    '<p>Esta versao tem zero JavaScript. Produtos ja estao no HTML.</p>',
    '<div id="v1"',
>',
    '  <h3>Catalogo:</h3>',
    '  <ul>',
    '    <li><a href="https://www.danajalecos.com.br/shop/jalecos/masculinos/manoel/jaleco-manoel-azul-marinho/">JALECO MASCULINO MANOEL AZUL MARINHO - R$ 209,00</a></li>',
    '    <li><a href="https://www.danajalecos.com.br/shop/jalecos/masculinos/samuel/jaleco-samuel-amarelo/">JALECO MASCULINO SAMUEL AMARELO - R$ 145,00</a></li>',
    '    <li><a href="https://www.danajalecos.com.br/shop/scrubs/masculinos/manga-curta/scrub-azul-marinho/">SCRUB MASCULINO MANGA CURTA AZUL MARINHO - R$ 177,65</a></li>',
    '  </ul>',
    '</div>',
    '',
    '<hr style="border: 3px solid black;">',
    '<h2 style="background: orange; padding: 10px;">VERSAO 2: COM JAVASCRIPT</h2>',
    '<p>Esta versao usa JavaScript para adicionar produtos.</p>',
    '<div id="v2">',
    '  <h3>Catalogo:</h3>',
    '  <ul id="lista"><li style="color: red; font-weight: bold;">Se voce ve isso, JavaScript NAO foi executado</li></ul>',
    '  <div id="resultado" style="color: red; font-weight: bold;">Status: JavaScript NAO executado</div>',
    '</div>',
    '',
    '<script>',
    'var prods = [',
    '  {n: "JALECO MASCULINO MANOEL AZUL MARINHO", l: "https://www.danajalecos.com.br/shop/jalecos/masculinos/manoel/jaleco-manoel-azul-marinho/", p: "R$ 209,00"},',
    '  {n: "JALECO MASCULINO SAMUEL AMARELO", l: "https://www.danajalecos.com.br/shop/jalecos/masculinos/samuel/jaleco-samuel-amarelo/", p: "R$ 145,00"},',
    '  {n: "SCRUB MASCULINO MANGA CURTA AZUL MARINHO", l: "https://www.danajalecos.com.br/shop/scrubs/masculinos/manga-curta/scrub-azul-marinho/", p: "R$ 177,65"}',
    '];',
    'function exec() {',
    '  var ul = document.getElementById("lista");',
    '  ul.innerHTML = "";',
    '  for (var i = 0; i < prods.length; i++) {',
    '    var li = document.createElement("li");',
    '    li.innerHTML = "<a href=\\"" + prods[i].l + "\\">" + prods[i].n + " - " + prods[i].p + "</a>";',
    '    ul.appendChild(li);',
    '  }',
    '  document.getElementById("resultado").innerHTML = "<div style=\\"color: green; font-weight: bold;\\">Status: JavaScript FOI EXECUTADO - " + prods.length + " produtos</div>";',
    '}',
    'setTimeout(exec, 50);',
    '</script>',
    '',
    '<hr style="border: 3px solid black;">',
    '<h2>PERGUNTA PARA O STEVO:</h2>',
    '<p><strong>1. Voce consegue ver a VERSAO 1 (fundo amarelo)?</strong></p>',
    '<p><strong>2. Quantos produtos aparecem na VERSAO 1?</strong></p>',
    '<p><strong>3. Voce consegue ver a VERSAO 2 (fundo laranja)?</strong></p>',
    '<p><strong>4. Na VERSAO 2, o status e verde (JavaScript FOI EXECUTADO) ou vermelho (JavaScript NAO executado)?</strong></p>',
    '',
    '</body>',
    '</html>'
  ].join('\n');
  
  res.status(200).send(html);
}
